//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EthioSpark.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public Address()
        {
            this.Users = new HashSet<User>();
        }
    
        public int Id { get; set; }
        public string Zipcode { get; set; }
        public int CityCd { get; set; }
        public int CountryCd { get; set; }
    
        public virtual CodeValue CityCodeValue { get; set; }
        public virtual CodeValue CountryCodeValue { get; set; }
        public virtual ICollection<User> Users { get; set; }
    }
}
