//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EthioSpark.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CodeValue
    {
        public CodeValue()
        {
            this.CityAddresses = new HashSet<Address>();
            this.CountryAddresses = new HashSet<Address>();
            this.BodyTypeUsers = new HashSet<User>();
            this.DrinkingHabitUsers = new HashSet<User>();
            this.EducationUsers = new HashSet<User>();
            this.EthnicityUsers = new HashSet<User>();
            this.HeightUsers = new HashSet<User>();
            this.ReligionUsers = new HashSet<User>();
            this.SmokingHabitUsers = new HashSet<User>();
        }
    
        public int Id { get; set; }
        public int CodeSetId { get; set; }
        public string DisplayName { get; set; }
        public string Meaning { get; set; }
    
        public virtual CodeSet CodeSet { get; set; }
        public virtual ICollection<Address> CityAddresses { get; set; }
        public virtual ICollection<Address> CountryAddresses { get; set; }
        public virtual ICollection<User> BodyTypeUsers { get; set; }
        public virtual ICollection<User> DrinkingHabitUsers { get; set; }
        public virtual ICollection<User> EducationUsers { get; set; }
        public virtual ICollection<User> EthnicityUsers { get; set; }
        public virtual ICollection<User> HeightUsers { get; set; }
        public virtual ICollection<User> ReligionUsers { get; set; }
        public virtual ICollection<User> SmokingHabitUsers { get; set; }
    }
}
