//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EthioSpark.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CodeSet
    {
        public CodeSet()
        {
            this.CodeValue = new HashSet<CodeValue>();
        }
    
        public int Id { get; set; }
        public string DisplayName { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<CodeValue> CodeValue { get; set; }
    }
}
