//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EthioSpark.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Pictures = new HashSet<Picture>();
        }
    
        public int Id { get; set; }
        public int MembershipUserId { get; set; }
        public int AddressId { get; set; }
        public sbyte Gender { get; set; }
        public sbyte SeekingGender { get; set; }
        public System.DateTime Dob { get; set; }
        public string AboutMe { get; set; }
        public string Occupation { get; set; }
        public Nullable<bool> HasKids { get; set; }
        public Nullable<int> EducationCd { get; set; }
        public Nullable<int> EthnicityCd { get; set; }
        public Nullable<int> ReligionCd { get; set; }
        public Nullable<int> HeightCd { get; set; }
        public Nullable<int> BodyTypeCd { get; set; }
        public Nullable<int> SmokingHabitCd { get; set; }
        public Nullable<int> DrinkingHabitCd { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual CodeValue BodyTypeCodeValue { get; set; }
        public virtual CodeValue DrinkingHabitCodeValue { get; set; }
        public virtual CodeValue EducationCodeValue { get; set; }
        public virtual CodeValue EthnicityCodeValue { get; set; }
        public virtual CodeValue HeightCodeValue { get; set; }
        public virtual CodeValue ReligionCodeValue { get; set; }
        public virtual CodeValue SmokingHabitCodeValue { get; set; }
        public virtual ICollection<Picture> Pictures { get; set; }
    }
}
